# Generated by Django 5.0.7 on 2024-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("register_time", models.DateField()),
                ("gmail", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=200)),
            ],
        ),
    ]
