# Generated by Django 5.0.7 on 2024-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_customsinfo_gmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsinfo",
            name="register_time",
            field=models.DateTimeField(),
        ),
    ]
