# Generated by Django 5.0.7 on 2024-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_customsinfo_register_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="customs_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("register_time", models.DateTimeField()),
                ("gmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(name="CustomsInfo",),
    ]
