# Generated by Django 5.0.7 on 2024-07-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_customs_info_delete_customsinfo"),
    ]

    operations = [
        migrations.RenameModel(old_name="customs_Info", new_name="CustomsInfo",),
    ]
