# Generated by Django 5.0.7 on 2024-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_customs_info_customsinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("register_time", models.DateTimeField()),
                ("gmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=200)),
                ("display", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MemberInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("register_date", models.DateField()),
                ("gmail", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("igAddr", models.CharField(max_length=30)),
                ("fbAddr", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("photo", models.CharField(max_length=50)),
                ("display", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(name="CustomsInfo",),
    ]
