# Generated by Django 5.0.7 on 2024-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_custominfo_memberinfo_delete_customsinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceName", models.CharField(max_length=20)),
                ("serviceDescription", models.CharField(max_length=200)),
                ("serviceImage", models.CharField(max_length=20)),
                ("exampleGitHubLink", models.CharField(max_length=30)),
                ("exampleDescription", models.CharField(max_length=200)),
                ("exampleContributor", models.CharField(max_length=20)),
                ("exampleStartTime", models.DateField()),
                ("exampleEndTime", models.DateField()),
                ("exampleImage", models.CharField(max_length=20)),
                ("display", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="memberinfo",
            name="gitHubLink",
            field=models.CharField(default="", max_length=30),
        ),
    ]
