# Generated by Django 5.0.7 on 2024-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_serviceinfo_memberinfo_githublink"),
    ]

    operations = [
        migrations.AddField(
            model_name="custominfo",
            name="photo",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="memberinfo",
            name="photo",
            field=models.CharField(default="", max_length=20),
        ),
    ]
