# Generated by Django 5.0.7 on 2024-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_custominfo_photo_alter_memberinfo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberinfo",
            name="photo",
            field=models.CharField(default="images/client.jpg", max_length=20),
        ),
    ]
